
import type { Tool, FilterOptions, TrendData, ApplicationType, TestType, OperatingSystem, CodingRequirement, CodingLanguage, PricingModel, ReportingAnalytics, RoiTimePoint } from './types';
import { ALL_FILTER_VALUE } from '../lib/constants';

export const ALL_APPLICATION_TYPES: ApplicationType[] = ["Web", "Mobile", "API", "Desktop", "Backend"];
export const ALL_TEST_TYPES: TestType[] = ["UI Testing", "API Testing", "Performance Testing", "Security Testing", "Unit Testing", "E2E Testing"];
export const ALL_OPERATING_SYSTEMS: OperatingSystem[] = ["Windows", "macOS", "Linux", "Android", "iOS", "Cross-Platform"];
export const ALL_CODING_REQUIREMENTS: CodingRequirement[] = ["No-Code", "Low-Code", "Scripting", "AI/ML"];
export const ALL_CODING_LANGUAGES: CodingLanguage[] = ["JavaScript", "Python", "Java", "C#", "Ruby", "Go", "Swift", "Kotlin", "PHP", "N/A"];
export const ALL_PRICING_MODELS: PricingModel[] = ["Free", "Freemium", "Subscription", "One-time Purchase", "Open Source"];
export const ALL_REPORTING_ANALYTICS: ReportingAnalytics[] = ["Basic", "Advanced", "Customizable", "Integration-friendly", "Real-time"];


export const filterOptionsData: FilterOptions = {
  applicationTypes: [{ value: ALL_FILTER_VALUE, label: "All Applications" }, ...ALL_APPLICATION_TYPES.map(val => ({ value: val, label: val }))],
  testTypes: [{ value: ALL_FILTER_VALUE, label: "All Test Types" }, ...ALL_TEST_TYPES.map(val => ({ value: val, label: val }))],
  operatingSystems: [{ value: ALL_FILTER_VALUE, label: "All OS" }, ...ALL_OPERATING_SYSTEMS.map(val => ({ value: val, label: val }))],
  codingRequirements: [{ value: ALL_FILTER_VALUE, label: "Any Requirement" }, ...ALL_CODING_REQUIREMENTS.map(val => ({ value: val, label: val }))],
  codingLanguages: [{ value: ALL_FILTER_VALUE, label: "Any Language" }, ...ALL_CODING_LANGUAGES.map(val => ({ value: val, label: val }))],
  pricingModels: [{ value: ALL_FILTER_VALUE, label: "Any Model" }, ...ALL_PRICING_MODELS.map(val => ({ value: val, label: val }))],
  reportingAnalytics: [{ value: ALL_FILTER_VALUE, label: "Any Analytics" }, ...ALL_REPORTING_ANALYTICS.map(val => ({ value: val, label: val }))],
};

export const mockToolsData: Tool[] = [
  {
    id: "1",
    name: "Selenium",
    score: 8.7,
    logoUrl: "https://placehold.co/60x60.png",
    dataAiHint: "Selenium logo",
    applicationTypes: ["Web"],
    testTypes: ["UI Testing", "E2E Testing"],
    operatingSystems: ["Windows", "macOS", "Linux", "Cross-Platform"],
    codingRequirements: ["Scripting"],
    codingLanguages: ["Java", "Python", "C#", "Ruby", "JavaScript"],
    pricingModels: ["Open Source"],
    reportingAnalytics: ["Basic", "Integration-friendly"],
    strengths: ["Highly flexible and extensible", "Large community support", "Supports multiple languages"],
    weaknesses: ["Steep learning curve", "Requires coding knowledge", "Setup can be complex"],
    pdfLink: "/pdfs/selenium-guide.pdf",
    websiteUrl: "https://www.selenium.dev/",
    roiProjection: [
      { month: 1, roi: 50 }, { month: 2, roi: 55 }, { month: 3, roi: 62 },
      { month: 4, roi: 70 }, { month: 5, roi: 75 }, { month: 6, roi: 78 }
    ],
    initialSetupTime: "3-5 days",
    maintenanceOverhead: "High - Requires skilled engineers for script maintenance",
    testCreationSpeed: "Moderate - Depends on element locator strategy and framework",
    scriptReusability: "High - With proper design patterns (e.g., Page Object Model)",
    parallelExecutionSupport: "Excellent - Via Selenium Grid or cloud providers",
    testCaseCreationEffort: "Moderate to High - Pure scripting approach",
    skillRequirement: "High - Strong coding skills (Java, Python, C# etc.) needed",
    overallAutomationCoverage: "Very High - Can automate almost any web interaction",
    totalCostOfOwnership: "Medium - Open source, but skilled resource costs can be high",
  },
  {
    id: "2",
    name: "Playwright",
    score: 9.2,
    logoUrl: "https://placehold.co/60x60.png",
    dataAiHint: "Playwright logo",
    applicationTypes: ["Web"],
    testTypes: ["UI Testing", "API Testing", "E2E Testing"],
    operatingSystems: ["Windows", "macOS", "Linux", "Cross-Platform"],
    codingRequirements: ["Scripting"],
    codingLanguages: ["JavaScript", "Python", "Java", "C#"],
    pricingModels: ["Open Source"],
    reportingAnalytics: ["Advanced", "Integration-friendly"],
    strengths: ["Modern architecture", "Auto-waits and rich selectors", "Cross-browser and cross-language"],
    weaknesses: ["Younger community than Selenium", "Can be resource-intensive"],
    pdfLink: "/pdfs/playwright-guide.pdf",
    websiteUrl: "https://playwright.dev/",
    roiProjection: [
      { month: 1, roi: 60 }, { month: 2, roi: 68 }, { month: 3, roi: 75 },
      { month: 4, roi: 82 }, { month: 5, roi: 88 }, { month: 6, roi: 90 }
    ],
    initialSetupTime: "1-2 days",
    maintenanceOverhead: "Medium - Auto-waits reduce flakiness",
    testCreationSpeed: "High - Powerful selectors and tooling",
    scriptReusability: "High - Supports modern coding practices",
    parallelExecutionSupport: "Excellent - Built-in sharding and parallel capabilities",
    testCaseCreationEffort: "Moderate - Efficient scripting",
    skillRequirement: "Medium to High - Coding skills (JS, Python, etc.) beneficial",
    overallAutomationCoverage: "Very High - Handles complex scenarios well",
    totalCostOfOwnership: "Low to Medium - Open source, good developer experience",
  },
  {
    id: "3",
    name: "Cypress",
    score: 9.0,
    logoUrl: "https://placehold.co/60x60.png",
    dataAiHint: "Cypress logo",
    applicationTypes: ["Web"],
    testTypes: ["UI Testing", "E2E Testing"],
    operatingSystems: ["Windows", "macOS", "Linux"],
    codingRequirements: ["Scripting"],
    codingLanguages: ["JavaScript"],
    pricingModels: ["Open Source", "Subscription"],
    reportingAnalytics: ["Advanced", "Real-time"],
    strengths: ["Fast and reliable test execution", "Excellent debugging tools", "Easy to set up"],
    weaknesses: ["Only supports JavaScript", "Limited cross-origin support in some cases"],
    pdfLink: "/pdfs/cypress-guide.pdf",
    websiteUrl: "https://www.cypress.io/",
    roiProjection: [
      { month: 1, roi: 55 }, { month: 2, roi: 65 }, { month: 3, roi: 72 },
      { month: 4, roi: 78 }, { month: 5, roi: 83 }, { month: 6, roi: 85 }
    ],
    initialSetupTime: "1 day",
    maintenanceOverhead: "Low to Medium - Good selector engine, time-travel debugging",
    testCreationSpeed: "Very High - Interactive runner, easy API",
    scriptReusability: "Medium to High - JavaScript ecosystem",
    parallelExecutionSupport: "Good - Via Cypress Dashboard (paid) or custom setup",
    testCaseCreationEffort: "Low to Moderate - Developer-friendly",
    skillRequirement: "Medium - JavaScript knowledge required",
    overallAutomationCoverage: "High - Primarily for web applications",
    totalCostOfOwnership: "Low (Open Source) to Medium (Dashboard)",
  },
  {
    id: "4",
    name: "Testim",
    score: 8.5,
    logoUrl: "https://placehold.co/60x60.png",
    dataAiHint: "Testim logo",
    applicationTypes: ["Web"],
    testTypes: ["UI Testing", "E2E Testing"],
    operatingSystems: ["Cross-Platform"],
    codingRequirements: ["AI/ML", "Low-Code"],
    codingLanguages: ["JavaScript", "N/A"],
    pricingModels: ["Subscription"],
    reportingAnalytics: ["Advanced", "Customizable"],
    strengths: ["AI-powered locators for stability", "Fast authoring with record & playback", "Good for agile teams"],
    weaknesses: ["Can be expensive for large teams", "Some advanced scenarios may still require code"],
    pdfLink: "/pdfs/testim-guide.pdf",
    websiteUrl: "https://www.testim.io/",
    roiProjection: [
      { month: 1, roi: 65 }, { month: 2, roi: 72 }, { month: 3, roi: 78 },
      { month: 4, roi: 85 }, { month: 5, roi: 90 }, { month: 6, roi: 92 }
    ],
    initialSetupTime: "Less than 1 day",
    maintenanceOverhead: "Very Low - AI-powered self-healing locators",
    testCreationSpeed: "Very High - Record, playback, and AI suggestions",
    scriptReusability: "High - Reusable groups and components",
    parallelExecutionSupport: "Excellent - Cloud-based parallel execution",
    testCaseCreationEffort: "Very Low - Minimal coding required for most cases",
    skillRequirement: "Low - Suitable for manual testers and less technical users",
    overallAutomationCoverage: "High - Focus on UI and E2E for web",
    totalCostOfOwnership: "High - Subscription-based, depends on scale",
  },
  {
    id: "5",
    name: "Postman",
    score: 9.1,
    logoUrl: "https://placehold.co/60x60.png",
    dataAiHint: "Postman logo",
    applicationTypes: ["API"],
    testTypes: ["API Testing"],
    operatingSystems: ["Windows", "macOS", "Linux", "Cross-Platform"],
    codingRequirements: ["Low-Code", "Scripting"],
    codingLanguages: ["JavaScript", "N/A"],
    pricingModels: ["Freemium", "Subscription"],
    reportingAnalytics: ["Advanced", "Integration-friendly"],
    strengths: ["User-friendly interface for API development and testing", "Collaboration features", "Extensive integrations"],
    weaknesses: ["Performance testing capabilities are basic", "Can become slow with large collections"],
    pdfLink: "/pdfs/postman-guide.pdf",
    websiteUrl: "https://www.postman.com/",
    roiProjection: [
      { month: 1, roi: 70 }, { month: 2, roi: 73 }, { month: 3, roi: 76 },
      { month: 4, roi: 78 }, { month: 5, roi: 80 }, { month: 6, roi: 81 }
    ],
    initialSetupTime: "Minutes to hours",
    maintenanceOverhead: "Low - GUI based, version control for collections",
    testCreationSpeed: "Very High - Easy to create requests and assertions",
    scriptReusability: "High - Collections, environments, variables",
    parallelExecutionSupport: "Good - Via Newman CLI and CI/CD integrations",
    testCaseCreationEffort: "Low - Primarily GUI-driven with scripting options",
    skillRequirement: "Low to Medium - Basic understanding of APIs, JS for advanced scripts",
    overallAutomationCoverage: "Very High - For API functional and integration testing",
    totalCostOfOwnership: "Low (Freemium) to Medium (Team/Enterprise)",
  },
  {
    id: "6",
    name: "JMeter",
    score: 8.3,
    logoUrl: "https://placehold.co/60x60.png",
    dataAiHint: "JMeter logo",
    applicationTypes: ["Web", "API", "Backend"],
    testTypes: ["Performance Testing"],
    operatingSystems: ["Windows", "macOS", "Linux", "Cross-Platform"],
    codingRequirements: ["Scripting", "Low-Code"],
    codingLanguages: ["Java", "N/A"], // Groovy/BeanShell for scripting
    pricingModels: ["Open Source"],
    reportingAnalytics: ["Advanced", "Customizable"],
    strengths: ["Powerful and versatile for load testing", "Supports various protocols", "Extensible with plugins"],
    weaknesses: ["UI can be intimidating for beginners", "Requires significant resources for large tests"],
    pdfLink: "/pdfs/jmeter-guide.pdf",
    websiteUrl: "https://jmeter.apache.org/",
    roiProjection: [
      { month: 1, roi: 40 }, { month: 2, roi: 48 }, { month: 3, roi: 55 },
      { month: 4, roi: 60 }, { month: 5, roi: 65 }, { month: 6, roi: 70 }
    ],
    initialSetupTime: "2-3 days",
    maintenanceOverhead: "Medium - Test plans can become complex",
    testCreationSpeed: "Moderate - GUI with scripting elements",
    scriptReusability: "Medium - Test fragments and modules",
    parallelExecutionSupport: "Good - Distributed testing setup",
    testCaseCreationEffort: "Moderate - Requires understanding of performance concepts",
    skillRequirement: "Medium to High - Performance testing knowledge, some scripting",
    overallAutomationCoverage: "High - For performance, load, and stress testing",
    totalCostOfOwnership: "Low - Open source, but infra for distributed tests costs",
  },
  {
    id: "7",
    name: "Katalon Studio",
    score: 8.6,
    logoUrl: "https://placehold.co/60x60.png",
    dataAiHint: "Katalon Studio logo",
    applicationTypes: ["Web", "Mobile", "API", "Desktop"],
    testTypes: ["UI Testing", "API Testing", "E2E Testing"],
    operatingSystems: ["Windows", "macOS", "Linux"],
    codingRequirements: ["Low-Code", "Scripting"],
    codingLanguages: ["Groovy", "Java"],
    pricingModels: ["Freemium", "Subscription"],
    reportingAnalytics: ["Advanced", "Integration-friendly"],
    strengths: ["Comprehensive feature set", "Supports multiple application types", "Good for beginners and experienced testers"],
    weaknesses: ["Can be slower than some specialized tools", "Enterprise features are paid"],
    pdfLink: "/pdfs/katalon-guide.pdf",
    websiteUrl: "https://katalon.com/",
    roiProjection: [
      { month: 1, roi: 58 }, { month: 2, roi: 63 }, { month: 3, roi: 68 },
      { month: 4, roi: 72 }, { month: 5, roi: 76 }, { month: 6, roi: 78 }
    ],
    initialSetupTime: "1-2 days",
    maintenanceOverhead: "Medium - Object repository helps, but UI changes impact",
    testCreationSpeed: "High - Record/playback, manual mode, script mode",
    scriptReusability: "High - Keywords, test listeners, page object model support",
    parallelExecutionSupport: "Good - Via TestOps (paid) or custom configuration",
    testCaseCreationEffort: "Low to Moderate - Versatile options",
    skillRequirement: "Low to Medium - Groovy/Java for advanced scripting",
    overallAutomationCoverage: "Very High - Broad application type support",
    totalCostOfOwnership: "Medium - Freemium with paid enterprise features",
  },
   {
    id: "8",
    name: "Appium",
    score: 8.8,
    logoUrl: "https://placehold.co/60x60.png",
    dataAiHint: "Appium logo",
    applicationTypes: ["Mobile"],
    testTypes: ["UI Testing", "E2E Testing"],
    operatingSystems: ["Android", "iOS", "Cross-Platform"],
    codingRequirements: ["Scripting"],
    codingLanguages: ["Java", "Python", "JavaScript", "Ruby", "C#"],
    pricingModels: ["Open Source"],
    reportingAnalytics: ["Basic", "Integration-friendly"],
    strengths: ["Cross-platform mobile testing", "Supports native, hybrid, and mobile web apps", "Large community"],
    weaknesses: ["Setup can be challenging", "Execution speed can vary"],
    pdfLink: "/pdfs/appium-guide.pdf",
    websiteUrl: "https://appium.io/",
    roiProjection: [
      { month: 1, roi: 52 }, { month: 2, roi: 60 }, { month: 3, roi: 67 },
      { month: 4, roi: 73 }, { month: 5, roi: 78 }, { month: 6, roi: 82 }
    ],
    initialSetupTime: "3-5 days",
    maintenanceOverhead: "High - Mobile flakiness, OS updates",
    testCreationSpeed: "Moderate - Requires robust locator strategies",
    scriptReusability: "Medium to High - With good framework design",
    parallelExecutionSupport: "Good - With Selenium Grid or cloud mobile device farms",
    testCaseCreationEffort: "Moderate to High - Scripting for mobile interactions",
    skillRequirement: "High - Mobile automation concepts, coding skills",
    overallAutomationCoverage: "High - For native and hybrid mobile apps",
    totalCostOfOwnership: "Medium - Open source, but device farm/cloud costs",
  },
];

export const trendDataPerTestType: TrendData = {
  "UI Testing": {
    testType: "UI Testing",
    mostWidelyUsedTool: "Selenium",
    trendingTool: "Playwright",
    topRatedTool: "Cypress",
    aiPoweredTool: "Testim",
    enterpriseReadyTool: "Katalon Studio",
  },
  "API Testing": {
    testType: "API Testing",
    mostWidelyUsedTool: "Postman",
    trendingTool: "Playwright", // Playwright has API testing capabilities
    topRatedTool: "Postman", // Often cited as top for ease of use and features
    aiPoweredTool: "Testim (for UI, some API)", // Placeholder, API specific AI tools exist
    enterpriseReadyTool: "Katalon Studio", // Good API testing features
  },
  "Performance Testing": {
    testType: "Performance Testing",
    mostWidelyUsedTool: "JMeter",
    trendingTool: "k6",
    topRatedTool: "Grafana k6", // k6 often gets high ratings for modern perf testing
    aiPoweredTool: "LoadNinja", // AI-powered performance testing
    enterpriseReadyTool: "LoadRunner",
  },
    "Security Testing": {
    testType: "Security Testing",
    mostWidelyUsedTool: "OWASP ZAP",
    trendingTool: "Burp Suite",
    topRatedTool: "Burp Suite Professional",
    aiPoweredTool: "Invicti (formerly Netsparker)",
    enterpriseReadyTool: "Veracode",
  },
  "Unit Testing": {
    testType: "Unit Testing",
    mostWidelyUsedTool: "JUnit (Java), PyTest (Python), Jest (JS)", // Varies by language
    trendingTool: "Jest (JS), Mockito (Java)",
    topRatedTool: "PyTest (Python)",
    aiPoweredTool: "GitHub Copilot (assists writing tests)",
    enterpriseReadyTool: "Language-specific frameworks (e.g. NUnit for C#)",
  },
  "E2E Testing": {
    testType: "E2E Testing",
    mostWidelyUsedTool: "Selenium",
    trendingTool: "Playwright",
    topRatedTool: "Cypress",
    aiPoweredTool: "Testim",
    enterpriseReadyTool: "Katalon Studio",
  },
  "Default": { // Fallback if selectedTestType is not found
    testType: "General Testing",
    mostWidelyUsedTool: "Selenium",
    trendingTool: "Playwright",
    topRatedTool: "Cypress",
    aiPoweredTool: "Testim",
    enterpriseReadyTool: "Katalon Studio",
  }
};
